### ISSUE TITLE
google fonts inside webtemplate (remove fonts or store locally)

### ISSUE THREAD

**Issue by mechstrategen** [OddDev/bogenkino#26]
inside the webtemtplate file index.html there are google fonts included that were loaded from the google server. This could be a problem regarding data protection regulation (DSGVO).  It would be better to store them local or remove them complete.

**Comment by sfsarchery** [comment]
Additional the vimeo player is loaded from vimeo. Maybe it is also possible to include the player as a local resource.

**Comment by OddDev** [comment]
Fixed with https://github.com/OddDev/bogenkino/commit/2f68afe7aa566198f6bad2045e0235ac0871b3fc
